namespace: todo

backend:
  image: karthick1729/todo-backend:1.0
  replicas: 2

frontend:
  image: karthick1729/todo-frontend:1.0
  replicas: 2

postgres:
  image: postgres:14
  storage: 1Gi

ingress:
  host: todo.local