apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vicky442001/3-tier-app.git
    targetRevision: main
    path: helm-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: todo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true